### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [yisar/deku#5]

**Comment by yisar** [comment]
哈哈哈哈哈哈挺好的，俺老早就 star 啦

就是吧……有点懒，不想写文档::>_<::

以前写过，然后写完就扔那儿了::>_<::

**Comment by xcatliu** [comment]
哈哈，文档还是很重要滴，那等你完成文档后我可以帮助搭建网站哈

PS：仅有一个 README.md 也是可以构建为一个网页的哦

**Comment by yisar** [comment]
阔，阔以，fre 应该比较需要文档
https://github.com/yisar/fre
容我想想咋写::>_<::
